version: '3.8'

services:
  postgres:
    image: 'postgres:alpine'
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST: '${DB_HOST}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - jaw-dev-network
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - jaw-dev-network
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost:3000/api/healthz']
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3

volumes:
  postgres-data:
    driver: local

networks:
  jaw-dev-network:
    driver: bridge
